# Xcode
# Build, test, and archive an Xcode workspace on macOS.
# Add steps that install certificates, test, sign, and distribute an app, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/xcode

trigger:
- master

pool:
  vmImage: 'macos-latest'

variables:
  - group: connect4

steps:
- task: InstallAppleCertificate@2
  inputs:
   certSecureFile: '$(p12FileName)'
   certPwd: '$(p12Password)'
   keychain: 'temp'
   deleteCert: true

- task: InstallAppleProvisioningProfile@1
  inputs:
   provisioningProfileLocation: 'secureFiles'
   provProfileSecureFile: '$(provisioningProfile)'
   removeProfile: true

- task: FlutterInstall@0
  inputs:
    channel: 'beta'

- bash: ./build-ipa.zsh
  env:
    FLUTTER_TOOL_PATH: $(FlutterToolPath)

- task: CopyFiles@2
  inputs:
    contents: 'dist/**/*.ipa'
    targetFolder: $(Build.ArtifactStagingDirectory)
    overWrite: true

- task: PublishBuildArtifacts@1
  inputs:
    pathToPublish: $(Build.ArtifactStagingDirectory)
    artifactName: 'iOS'
